FROM node:20-alpine AS base

RUN npm install -g pnpm

WORKDIR /user/src/app

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./turbo.json ./turbo.json
COPY ./apps/ws ./app/ws

RUN pnpm install --frozen-lockfile

RUN pnpm run db:generate

EXPOSE 8081

CMD [ "pnpm", "run", "start:ws" ]