FROM node:20-alpine AS base

RUN npm install -g pnpm

WORKDIR /user/src/app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY ./packages ./packages
COPY ./package.json ./package.json
COPY ./pnpm-lock.ymal ./pnpm-lock.ymal
COPY ./turbo.json ./turbo.json
COPY ./apps/frontend ./apps/frontend

RUN pnpm install --frozen-lockfile

RUN pnpm run db:generate

RUN DATABASE_URL=${DATABASE_URL} pnpm run build

EXPOSE 3000

CMD [ "pnpm", "run", "start:web" ]